apiVersion: v1
kind: Secret
metadata:
  name: vitalsync-db-secret
  namespace: default
  labels:
    app: vitalsync
type: Opaque
data:
  db-user: dml0YWxzeW5jX3VzZXI=
  db-password: Vml0YWxTeW5jMjAyNCE=
